name: COBOL Check Automation
on:
push:
branches: [ main ]
jobs:
cobol-check:
runs-on: ubuntu-latest
COBOL Programming
Course #4 3.2.0|
250217-2356
steps:
- uses: actions/checkout@v2
- name: Set up Java
uses: actions/setup-java@v2
with:
java-version: '11'
- name: Run COBOL Check
env:
ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
run: |
# Here we'll add our commands to run cobolcheck
echo "Running COBOL Check"
# Add actual cobolcheck commands here
